apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: "mongo:4.2.17-bionic"
        env:
          - name: MONGO_INITDB_DATABASE
            value:  'logs'
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "password"
        ports:
          - containerPort: 27017

---
# Define the service that's associated with this deployment

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo #  This line specifies the label name: mongo, which matches the label used in the Deployment's selector.
  ports:
    - protocol: TCP
      name: main-port
      port: 27017
      targetPort: 27017